import type { Metadata } from "next";
import { Montserrat, Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { DonationModalProvider } from "@/context/DonationModalContext";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat", // Optional: for Tailwind CSS
  display: "swap",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Myanmar Haemophilia Patient Association",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${openSans.variable}`}>
        <DonationModalProvider>
          <Navbar />
          {children}
        </DonationModalProvider>
      </body>
    </html>
  );
}
